#!/usr/bin/python3 -B

"""
Converts Bayer raw PGM/PNG/RAW images into RGB PPM.
"""

# pylint: disable=invalid-name
# pylint: disable=c-extension-no-member
# pylint: disable=wrong-import-position
# pylint: disable=too-many-locals
# pylint: disable=too-many-instance-attributes
# pylint: disable=too-many-branches
# pylint: disable=too-many-statements
# pylint: disable=too-few-public-methods

from __future__ import print_function as __print  # hide from help

import sys              # built-in library
import os               # built-in library
import signal           # built-in library
import time             # built-in library
import numpy as np      # pip install numpy
import imgio            # pip install imgio
import argv             # local import: argv.py
import isptools         # local import: isptools.py
import demosaic         # local import: demosaic.py

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'multiproc'))

import multiproc        # submodule import: multiproc.py

class ISPConfig(object):
    def __init__(self):
        self.width = None             # None | <uint>
        self.height = None            # None | <uint>
        self.bpp = None               # None | <uint>
        self.blackLevel = None        # AUTO | <float>
        self.whiteLevel = None        # AUTO | MAX | <float>
        self.bayerPattern = None      # RGGB | GBRG | BGGR | GRBG
        self.gic = None               # None | <float>
        self.wb = None                # None | tuple(<float>, <float>)
        self.gamma = None             # None | sRGB | rec709
        self.outbpp = None            # None | <uint>
        self.demosaic = True          # currently hardcoded
        self.dryRun = False           # currently hardcoded
        self.outformat = "ppm"        # currently hardcoded


def bayer2ppm(config, infilename, outfilename):
    print("Converting %s to %s..."%(infilename, config.outformat.upper()))
    elapsed = lambda t0: (time.time() - t0) * 1000
    tStart = t0 = time.time()
    outbpp = config.outbpp
    blackLevel = config.blackLevel
    whiteLevel = config.whiteLevel
    bayerPattern = config.bayerPattern
    raw, maxval = imgio.imread(infilename, config.width, config.height, config.bpp)
    height, width = raw.shape[:2]
    cropRow = np.index_exp[:-1, :]
    cropCol = np.index_exp[:, :-1]
    raw = raw[cropRow] if (height % 2) != 0 else raw  # must have even number of rows
    raw = raw[cropCol] if (width % 2) != 0 else raw   # must have even number of columns
    height, width = raw.shape[:2]
    bpp = np.log2(maxval + 1)
    print("%8.2f ms - reading input file: %d x %d, %d bpp"%(elapsed(t0), width, height, bpp))

    if isinstance(config.blackLevel, str):  # dtype: <unchanged>
        t0 = time.time()
        if config.blackLevel == "AUTO":
            blackLevel = isptools.blacklevel(raw, max_outliers=1000)
        print("%8.2f ms - estimating black level: %.2f (%s)"%(elapsed(t0), blackLevel, config.blackLevel))
        if blackLevel > maxval / 8.0:
            print("%sWARNING: Estimated black level is very high. Is this a genuine raw image?"%(' ' * 14))

    if isinstance(config.whiteLevel, str):  # dtype: <unchanged>
        t0 = time.time()
        if config.whiteLevel == "MAX":
            whiteLevel = maxval
        elif config.whiteLevel == "AUTO":
            whiteLevel = isptools.whitelevel(raw, max_outliers=100)
            print("%8.2f ms - estimating white level: %d"%(elapsed(t0), whiteLevel))

    if blackLevel > 0 or whiteLevel < maxval:  # dtype: uint16 / float32 ==> float32
        t0 = time.time()
        raw = raw.astype(np.float32)
        raw = np.clip(raw, blackLevel, whiteLevel)
        raw = raw - blackLevel
        scale = maxval / float(whiteLevel - blackLevel)
        raw = raw * scale
        print("%8.2f ms - rescaling from [%.2f, %.2f] to [0, %d]"%(elapsed(t0), blackLevel, whiteLevel, maxval))

    if config.gic or config.wb:  # dtype: uint16 / float32 ==> float32
        t0 = time.time()
        (gr, gb) = (config.gic, 1.00) if config.gic else (1.0, 1.0)
        (r, b) = config.wb if config.wb is not None else (1.0, 1.0)
        if bayerPattern == "RGGB":
            (c1, c2, c3, c4) = (r, gr, gb, b)
        elif bayerPattern == "BGGR":
            (c1, c2, c3, c4) = (b, gb, gr, r)
        elif bayerPattern == "GBRG":
            (c1, c2, c3, c4) = (gb, b, r, gr)
        elif bayerPattern == "GRBG":
            (c1, c2, c3, c4) = (gr, r, b, gb)
        raw = raw.astype(np.float32)
        raw[0::2, 0::2] *= c1
        raw[0::2, 1::2] *= c2
        raw[1::2, 0::2] *= c3
        raw[1::2, 1::2] *= c4
        print("%8.2f ms - applying per-channel gains: [R=%.3f, Gr=%.3f, Gb=%.3f, B=%.3f]"%(elapsed(t0), r, gr, gb, b))

    if config.demosaic:
        t0 = time.time()
        raw = raw.astype(np.float32)
        raw = demosaic.demosaic(raw, pattern=bayerPattern.lower(), method='hq_linear', clip=(0, maxval))
        print("%8.2f ms - demosaicing (high quality, %s)"%(elapsed(t0), bayerPattern))

    if config.gamma is not None:  # sRGB | rec709 | None
        t0 = time.time()
        raw = raw.astype(np.float32)
        raw = isptools.gamma(raw, maxval, config.gamma)
        print("%8.2f ms - applying gamma correction (%s)"%(elapsed(t0), config.gamma))

    if outbpp is not None and maxval != (2**outbpp - 1):
        t0 = time.time()
        newmaxval = 2**outbpp - 1
        raw = isptools.quantize(raw, maxval, newmaxval)
        maxval = newmaxval
        print("%8.2f ms - converting from %d bpp to %d bpp"%(elapsed(t0), bpp, outbpp))

    if raw.dtype not in [np.uint8, np.uint16]:
        t0 = time.time()
        oldtype = raw.dtype
        newtype = 'uint8' if maxval <= 255 else 'uint16'
        rounded = raw + 0.5
        raw = rounded.astype(newtype)
        print("%8.2f ms - converting from %s to %s"%(elapsed(t0), oldtype, newtype))

    if not config.dryRun:
        t0 = time.time()
        raw = np.clip(raw, 0, maxval)
        imgio.imwrite(outfilename, raw, maxval)
        print("%8.2f ms - writing demosaiced RGB to %s file"%(elapsed(t0), config.outformat.upper()))

    print("%8.2f ms - TOTAL\n"%(elapsed(tStart)))


class TerminationRequest(IOError):
    pass

def _onExit():
    raise TerminationRequest("Terminated by the user.")

def _enforce(expression, messageIfFalse):
    if not expression:
        print(messageIfFalse)
        sys.exit(-1)

def _process(config, infilespec):
    infilename = os.path.basename(infilespec)
    outfilename = infilename.rsplit('.', 1)[0] + "." + config.outformat
    bayer2ppm(config, infilespec, outfilename)

def _main():
    config = ISPConfig()
    config.width = argv.intval("--width")
    config.height = argv.intval("--height")
    config.bpp = argv.intval("--bpp", default=None, accepted=[8, 10, 12, 14, 16])
    config.bayerPattern = argv.stringval("--bayer", default="RGGB", accepted=["RGGB", "GBRG", "BGGR", "GRBG"])
    config.blackLevel = argv.floatstring("--blacklevel", default="AUTO", accepted=["AUTO"])
    config.whiteLevel = argv.floatstring("--whitelevel", default="MAX", accepted=["AUTO", "MAX"])
    config.gic = argv.floatval("--gic")
    config.wb = argv.floatpair("--wb")
    config.gamma = argv.stringval("--gamma", default=None, accepted=["rec709", "sRGB"])
    config.outbpp = argv.intval("--outbpp", default=None, accepted=[8, 10, 12, 14, 16])
    showHelp = argv.exists("--help")
    argv.exitIfAnyUnparsedOptions()

    if len(sys.argv) < 2 or showHelp:
        print("Usage: bayer2ppm [options] inputfile.[pgm|png] ...")
        print()
        print("  options:")
        print("    --width N                      image width in pixels (for .RAW only); default = None")
        print("    --height N                     image height in pixels (for .RAW only); default = None")
        print("    --bpp N                        bits per pixel (for .RAW only); default = None")
        print("    --bayer RGGB|GBRG|BGGR|GRBG    Bayer order of input file; default = RGGB")
        print("    --blacklevel N|AUTO            pixel value to subtract from all pixels; default = AUTO")
        print("    --whitelevel N|AUTO|MAX        pixel value to consider fully saturated; default = MAX")
        print("    --gic F                        multiply Gr pixels by F to fix green imbalance; default = 1.000")
        print("    --wb R B                       multiply R and B pixels by the given factors; default = 1.0 1.0")
        print("    --gamma sRGB|rec709            apply gamma according to sRGB or rec709; default = None")
        print("    --outbpp N                     output bit depth (None = keep original); default = None")
        print("    --help                         show this help message")
        print()
        print("  Converts the given 10/12/16-bit Bayer raw PGM/PNG/RAW file(s) into RGB PPM using a reference")
        print("  ISP pipeline written in Python.")
        print()
        sys.exit(-1)

    filenames, _ = argv.filenames(sys.argv[1:], [".pgm", ".png", ".raw"], sort=True)
    arguments = [(config, filename) for filename in filenames]
    numFiles = len(filenames)
    _enforce(numFiles > 0, "No valid raw Bayer PGM/PNG/RAW files to process. Terminating.")
    signal.signal(signal.SIGINT, lambda s, f: _onExit())  # Ctrl+C handler
    ncpu = multiproc.cpu_count()
    nproc = max(1, int(ncpu / 2))
    print("Processing %d image(s) using up to %d concurrent processes..."%(numFiles, nproc))
    try:
        t0 = time.time()
        multiproc.run(_process, arguments, nproc, raise_exceptions=False)
        elapsed = time.time() - t0
        perFile = float(elapsed) / numFiles * 1000
        if numFiles > 1:
            print("Processed %d files in %.1f seconds (%d ms per file)"%(numFiles, elapsed, perFile))
    except BaseException:
        import traceback
        traceback.print_exc()
    finally:
        signal.signal(signal.SIGINT, signal.SIG_DFL)

if __name__ == "__main__":
    _main()
